GoogleAPIKey: AIzaSyBO5KwerGn-ATJeYRuqimOm70TH0YfVkLY
bigtmp: ''
cov_filter: true
cov_merge: 100
cov_threshold_lower: 
cov_threshold_rel: null
cov_threshold_stdev: 2
cov_threshold_upper: 
db_scatter_factor: 0.15
final_prefix: 17-Semicossyphus
het_prior: 0.005
intervals: false
mappability_k: 150
mappability_merge: 100
mappability_min: 1
minD: 1
minNmer: 500
minP: 1
min_depth: 2
nClusters: 3
num_gvcf_intervals: 1
remote_reads: true
remote_reads_prefix: ccgp-raw-reads/17-Semicossyphus
resource_config: config/resources.yaml
samples: sample_sheets/TEST_17-Semicossyphus_workflow.csv
sentieon: true
sentieon_lic: 10.128.0.63:8990
CCGP: true
contig_size: 10000 # snps on contigs this size or smaller will be filtered from the final clean vcfs. Set to 0 to disable.
maf: 0.01 #snps with MAF below this value will be filtered from the final clean vcfs. Set to 0 to disable.
missingness: 0.75 #snps with missingness greater than this value will be filtered from the final clean vcfs. Set to 1 to disable.
scaffolds_to_exclude: "mtDNA,Y" #comma separated, no spaces list of scaffolds to exclude from final clean vcfs. Set to blank to disable.
